### ISSUE TITLE
Allow updates to a published post and integrate it in Altis workflows 

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-workflow#58] opened 2021-04-21 21:26 UTC
**User Story:**
As a user, I want to take a published post to the draft state so that I can update it and get necessary approvals before republishing it.

**Requirement:** 
The ability to get approvals / follow workflows on the revisions of an already published post. 

Acceptance Criteria:
Given: I create a redraft of a published post 
When: I want to republish it 
Then: I should be able to get the due approvals and follow existing workflow of a regular post before republishing it.

**Comment by rmccue** [comment] 2021-05-06 16:36
Duplicate of #57

**Closed by rmccue** 2021-05-06 16:36 UTC
